services:
  db:
    image: mariadb:11
    environment:
      MARIADB_ROOT_PASSWORD: ChangeMe
      MARIADB_DATABASE: app
      MARIADB_USER: app
      MARIADB_PASSWORD: ChangeMe
    ports:
      - "3307:3306"
    volumes:
      - ./data/db:/var/lib/mysql

  maildev:
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"