services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: ChangeMe
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data